// English dictionary. Mirrors nl.js key-for-key.
export default {
  taste: {
    matchGenres: '{genres} matches your highest-rated films',
    aboutThemes: 'about {themes}, your themes', and: ' and ',
    negGenre: 'note: {genre} actually scores low with you',
    yourEra: 'the \u0027{era}s are your era',
    nonEnglish: 'non-English, you watch a lot of that',
    strongRated: 'strongly rated ({score} at {n} votes)',
    barelyRated: { one: 'only {count} vote, so take that number with a grain of salt', other: 'only {count} votes, so take that number with a grain of salt' },
    obscure: 'nicely obscure, just like your taste',
  },
  similar: {
    title: 'More like {name}',
    seedThemes: 'Themes of this film: {themes}',
    loading: 'Searching smartly\u2026',
    shares: 'shares {themes}',
    tasteThemes: 'touches your themes: {themes}',
    genres: 'also {genres}',
    quality: 'highly rated ({score})',
    lang: 'same language as the original',
    both: 'doubly recommended by TMDB',
    onList: 'on your watchlist',
    none: 'The tool finds little here. Try another film as a starting point.',
    back: 'Back to the suggestions', viaRecommender: 'Via the smart recommender',
    close: 'Close',
  },
  remote: {
    title: '{host} wants to pick a film together',
    explain: 'Tap the films you would actually watch. Multiple is fine.',
    yourName: 'Your name', namePlaceholder: 'e.g. Pim',
    send: 'Send your vote', sending: 'Sending\u2026',
    pickAtLeast: 'Pick at least one film.', nameFirst: 'Fill in your name first.',
    sentTitle: 'Vote sent', sentWait: '{host} will close the round. This screen refreshes by itself.',
    changeVote: 'Change vote',
    winnerIs: 'It will be:', backToTool: 'To the tool',
    invalid: 'This voting round does not exist or has expired. Codes are valid for 24 hours.',
    loading: 'Loading voting round\u2026',
  },
  share: { eyebrow: "TONIGHT WE\u0027RE WATCHING" },
  nav: {
    navLabel: 'Main navigation',
    pick: 'Pick', bieb: 'Library', verken: 'Explore', avond: 'Movie night', inzicht: 'Insights', setup: 'Setup',
  },
  app: {
    storageBroken: 'Browser storage is full or blocked. Changes are no longer being saved. Free up space via Setup or leave private mode.',
    enriching: 'Fetching film data from TMDB\u2026 {done}/{total}', enrichErrCount: ' ({count} failed)', pause: 'Pause',
    tmdbKeyRejected: 'TMDB rejected your key. Check it in Setup.',
    enrichFailed: 'Fetching film data ran aground: {msg}',
    omdbStopLimit: { one: 'OMDb daily limit reached. {count} film has no scores yet. It will follow tomorrow.', other: 'OMDb daily limit reached. {count} films have no scores yet. They will follow tomorrow.' },
    omdbStopInvalid: { one: 'OMDb rejected your last key. {count} film has no scores yet. Check your keys in Setup.', other: 'OMDb rejected your last key. {count} films have no scores yet. Check your keys in Setup.' },
    omdbNoScores: 'Not a single OMDb score came in (0 of {done}).{err} See Setup for the test-run button and error detail.',
    omdbLastError: ' Last error: {msg}.',
    demoBanner: 'This is the <strong>demo watchlist</strong>, with sample films. Drop in your own export whenever you like.',
    demoReset: 'Clear demo and start over',
    omdbNudge: 'You currently see only TMDB scores. Free OMDb keys add IMDb, Rotten Tomatoes, Metacritic and the Nossy score. ',
    omdbNudgeLink: 'set up in Setup', omdbNudgeDismiss: 'No, TMDB is fine',
    needKeyNotice: 'Without a TMDB key there are no posters, scores or streaming services. Set it up in one minute in ',
    setupLink: 'Setup',
  },
  common: {
    decade: 'The \u0027{era}s', showMore: 'Show more ({count} left)', posterAlt: 'Poster of {name}', openAria: 'Open {title}',
    back: 'Back', close: 'Close', save: 'Save', cancel: 'Cancel', stop: 'Stop',
    loading: 'Loading\u2026', search: 'Search', clear: 'Clear', seen: 'Seen', shortlist: 'Shortlist',
    skip: 'Skip', showFilters: 'Show filters', hideFilters: 'Hide filters', hide: 'Hide',
    allYears: 'All years', anyDuration: 'Any length', anyScore: 'Any score',
    films_over: { one: '{count} film left', other: '{count} films left' },
  },
  sort: {
    titleAZ: 'Title A\u2013Z', newest: 'Newest first', oldest: 'Oldest first',
    highestScore: 'Highest score', shortest: 'Shortest first', longest: 'Longest first',
    yourRating: 'Your rating', bestScore: 'Best score first', popular: 'Most popular first',
    bestMatch: 'Best match for you', nossyScore: 'Nossy score (after loading)',
  },
  mood: {
    kort: 'Short evening', kort_desc: '105 min or shorter',
    topper: 'Proven hit', topper_desc: 'Nossy score 7.4+',
    parel: 'Hidden gem', parel_desc: 'Nossy score 7.0+ with few votes',
    klassieker: 'Classic', klassieker_desc: 'Made before 1990',
    vers: 'Fresh', vers_desc: '2020 or later',
  },
  pick: {
    source: 'Pick from', sourceWatchlist: 'Watchlist', sourceCount: '({count})',
    followupTitle: 'Your previous pick', followupQ: 'Did you watch it?',
    rateAria: 'Give {n} stars', seenNoStars: 'Seen, no stars', notWatched: 'Didn\u0027t watch',
    title: 'Pick', mood: 'In the mood for\u2026', genres: 'Genres',
    onlyMyServices: 'Only on my services', resetFilters: 'Reset filters',
    fromYear: 'From year', toYear: 'To year', maxMinutes: 'Max minutes',
    minScoreEx: 'Min score (e.g. 7)', maxRuntime: 'Maximum runtime', minScore: 'Minimum score',
    empty: 'No (unwatched) films in this selection. Adjust your filters or mood, or check whether the film data has been fetched.',
    noSimilar: 'Nothing similar found in your (unwatched) watchlist.',
    likePrev: 'Because it resembles your previous pick',
    reroll: 'Not feeling it? Pick again', pickFilm: 'Pick a film', moodContext: 'Mood: {mood}',
    poolCount: { one: '{count} film in your pool', other: '{count} films in your pool' }, poolExcludeSeen: ' (seen excluded)',
    smartTitle: 'Higher-rated films get a better chance; recently picked films less. Applies to every pick.',
    smartLabel: 'Smart pick:', on: 'on', off: 'off', filters: 'Filters', filtersActive: '(active)',
  },
  bieb: {
    title: 'Library', empty: 'No films yet',
    emptyHint: 'Load your Letterboxd export in Pick, and your whole collection will appear here to browse.',
    fromLibrary: 'From your library', yourWatchlist: 'Your watchlist', yourHistory: 'Your watch history',
    watchlist: 'Watchlist', searchPlaceholder: 'Search by title', searchLabel: 'Search your library',
    sortLabel: 'Sort by', periodLabel: 'Period', maxDurationLabel: 'Maximum length',
    onStreaming: 'On streaming:', nothingFound: 'Nothing found', hideSeen: 'Hide seen',
    noMatch: 'No film matches your search and filters. Try loosening them a little.',
    fromHistory: 'From your watch history', youGave: ' \u00b7 you gave {score} \u2605',
    header: { one: '{shown} of {count} film', other: '{shown} of {count} films' }, filtered: ' (filtered)',
    seenTab: 'Seen ({count})', jij: 'you gave {score} \u2605',
  },
  avond: {
    title: 'Movie night', needWatchlist: 'A watchlist first',
    needWatchlistHint: 'Load your Letterboxd export in Pick, then you can choose together here.',
    groupSpoke: 'The group has spoken.', survivedVetoes: 'Survived every veto',
    bracketWinner: 'Winner of the bracket', vetoRound: 'Veto round',
    vetoHint: 'Pass the phone around after each veto. The last film standing is the one you watch.',
    quarterfinal: 'Quarterfinal', semifinal: 'Semifinal', final: 'Final',
    pot: 'The pot', myWatchlist: 'My watchlist', loadOtherFriend: 'Load another friend',
    loadFriendWatchlist: "Load a friend's watchlist", year: 'Year', yearFrom: 'Year from', yearTot: 'Year to',
    from: 'from', to: 'to', noWatchlistInFile: 'No watchlist found in this file.',
    startVeto: 'Start veto', filtersOptional: 'Filters \u00b7 optional', filtersActive: 'Filters \u00b7 {count} films left',
    genre: 'Genre', maxDuration: 'Maximum length', minNossy: 'Minimum Nossy score',
    onlyStreaming: 'Only on streaming', tooFew: { one: 'Only {count} film left. Loosen a filter for a proper round.', other: 'Only {count} films left. Loosen a filter for a proper round.' },
    overlapCount: { one: '{count} film is on all your lists', other: '{count} films are on all your lists' },
    pageSub: { one: 'Choosing together without the debate: {count} candidate in the pot.', other: 'Choosing together without the debate: {count} candidates in the pot.' },
    vetoExplain: '{count} films on the table. Everyone strikes one in turn. Whatever survives is what you watch. Pass the phone around and done.',
    remoteTitle: 'Remote', startRemote: 'Start a remote voting round',
    remoteExplain: 'Everyone votes on their own phone, wherever they are.',
    remoteHow1: 'Start the round. The tool takes up to 12 films from the pot, so your filters above count.',
    remoteHow2: 'Share the link in your group chat. Voting works on any phone, no account or install needed.',
    remoteHow3: 'Close once everyone has voted. Most votes wins; the result also appears for the voters.',
    remoteWaitHint: 'Keep this screen open, it refreshes by itself. A vote can take up to a minute to arrive.',
    remoteValidity: 'The code is valid for 24 hours.',
    remoteCode: 'Code: {code}', copyLink: 'Copy share link', copied: 'Copied',
    votesIn: { one: '{count} vote in: {names}', other: '{count} votes in: {names}' },
    noVotesYet: 'No votes yet. This screen refreshes by itself.',
    closeRound: 'Close and pick the winner', stopRound: 'Stop the round',
    remoteVoteCount: { one: '{count} vote', other: '{count} votes' },
    kvMissing: 'The Worker does not know voting rounds yet. Follow the KV step in worker/OPZETTEN.md and try again.',
    remoteFailed: 'Starting the round failed: {msg}',
    overlapChip: 'Overlap with {names}', overlapChipEmpty: 'Overlap with a friend', removeFriendAria: 'Remove {name}\u0027s list',
    overlapTooFew: ': too few for a round, switch back to your own list',
    infoAria: 'Info about {name}',
    peek: 'A quick peek. The round continues.', startBracket: 'Start bracket',
    players: 'Players', playerCount: 'Number of players', min4: 'At least 4 unwatched films needed in the pot.',
    filtersOpt: 'Filters {suffix}', filtersOptSuffix: '\u00b7 optional', filtersActiveSuffix: { one: '\u00b7 {count} film left', other: '\u00b7 {count} films left' },
  },
  inzicht: {
    title: 'Insights', empty: 'No data yet',
    emptyHint: 'Load your watchlist in Pick. Your taste profile will appear here afterwards.',
    subtitle: 'Your taste, read from your watchlist{extra}.', andRatings: ' and ratings',
    profileTitle: 'Your taste profile, what the recommendations steer on',
    profileYoung: 'Still early: give more stars on Letterboxd (or load your ratings.csv) and this profile gets sharper. What there is so far:',
    rhythm: 'Your watching rhythm, last 12 months',
    rhythmLine: { one: '{count} film watched, peak in {month}', other: '{count} films watched, peak in {month}' },
    rewatchLine: { one: 'of which {count} rewatch', other: 'of which {count} rewatches' },
    onWatchlist: 'On your watchlist', toWatch: 'Still to watch',
    famDeep: 'nicely into the deep end', famMix: 'a healthy mix of known and obscure', famEstablished: 'mostly established titles',
    watchMostly: 'predominantly', watchAlso: 'also happily', watchMainlyEn: 'mainly English-language, with the occasional',
    langFamLine: 'You watch {watch} <strong>{pct}% non-English</strong>, and in terms of familiarity your taste sits around <strong>{votes} votes</strong>: {verdict}.', avgRuntime: 'Avg. runtime',
    totalTime: 'Total watch time', avgTmdb: 'Avg. TMDB score', hours: '\u00b1{h} hours', min: '{m} min',
    genres: 'Genres', decades: 'Decades', directorsMulti: 'Directors with several films on your list',
    countries: 'Countries', prevPick: 'Earlier pick',
    lovesLine: 'You especially go for <strong>{genres}</strong>', lovesEra: ' from the <strong>{era}</strong>',
    dislikesLine: 'Less your thing: <strong>{genres}</strong>. The tool weighs these down in recommendations.',
    themesLine: 'Recurring themes in what you rate highly: <strong>{themes}</strong>. They steer "For you", and you can actively hunt on them.',
  },
  verken: {
    title: 'Explore', tabSearch: 'Search', tabForYou: 'For you',
    searchSub: 'Search the complete TMDB catalogue by title, creator or criteria, with your taste profile as the lens.',
    forYouSub: 'Your personal picks from your own films{ratings}. {count} suggestions, none of them on your list yet.',
    basedOnRatings: ', based on what you rated 4+ stars',
    needKeyTitle: 'A TMDB key first',
    needKeySub: 'Search the complete film database and discover films beyond your watchlist.',
    needKeyBody: 'Set your TMDB key in Setup. Then you can search the whole catalogue here. Load your watchlist in Pick for personal recommendations in "For you".',
    fromOutside: 'From outside your list', detailsLoading: 'Loading details\u2026',
    backToVerken: 'Back to Explore', bestMatchForYou: 'Best match for you',
    strongestRec: 'Most recommended', forNowEmpty: 'Nothing left for now',
    allRatedEmpty: 'You\u0027ve rated or skipped everything. Luckily TMDB is far from empty.',
    huntThemes: 'Hunt on my themes', huntThemesActive: '\u2713 Hunting on my themes', hunting: 'Theme hunt\u2026',
    yourThemes: 'Your themes: {themes}', huntTitle: 'Fetch films that share your strongest themes', foundOnThemes: 'Found on your themes: {themes}',
    viaProfile: 'Found via your taste profile', likeThis: 'Like', becauseYou: 'Because you', and: ' and ',
    loadFresh: 'Load fresh from TMDB', loadFreshMore: 'Load fresh from TMDB (\u00b160 new candidates)',
    tapping: 'Tapping\u2026', tappingTmdb: 'Tapping from TMDB\u2026', shortlistCopied: 'Shortlist copied.',
    removeShortAria: 'Remove {title} from shortlist',
    rejected: 'Rejected ({count}) \u00b7 {action}', rejHide: 'hide', rejShow: 'view and restore',
    fromOeuvre: 'From the oeuvre of {name}',
    rowOeuvre: 'More from {name}', rowTheme: 'Shares {themes} with your favourites',
    rowThemePlain: 'Around your themes', rowSeed: 'Because you rated {name} highly',
    rowProfile: 'Match your taste profile', rowsToggleAll: 'Show as one list',
    rowsToggleRows: 'Show in rows',
    moodPrompt: 'What are you after right now?',
    moodLight: 'Something light', moodDark: 'Something dark', moodShort: 'Shorter (< 1h45)',
    moodAcclaimed: 'Highly rated', moodSurprise: 'Surprise me',
    moodFocus: 'Focus on genre', moodClear: 'Clear',
    moodActive: 'Recommendations tuned to your mood',
    notForMe: 'Not for me', viewCard: 'View card', similar: 'More like this',
    nudgeMore: 'Noted. You\u0027ll now see a bit more {genre} in your recommendations.',
    nudgeLess: 'Noted. You\u0027ll now see a bit less {genre} in your recommendations.',
    blending: 'Blend engine is widening the pool\u2026 (similar films, oeuvres of your favourite directors, your profile)',
    inflow: 'Inflow: recommendations \u00b7 similar \u00b7 {oeuvres} oeuvres \u00b7 your profile{theme}. {count} candidates in total.',
    inflowTheme: ' \u00b7 {count} on theme',
    andOthers: ' (and {count} more)', ratedHigh: ' rated highly', onYourList: ' have on your list',
    viaRoutes: ' \u00b7 via {count} routes', showMore: 'Show more ({count} left)',
    hiddenPanel: '{count} skipped', restore: 'Restore {title}', restoreTitle: 'Put back as recommendation',
  },
  zoek: {
    placeholder: 'Search by title or creator, or leave empty and filter below',
    searchLabel: 'Search by title or creator', onMyTaste: 'On my taste', pearlPreset: 'Hidden-gem preset',
    genres: 'Genres', period: 'Period', language: 'Language', minScoreLabel: 'Minimum score',
    runtime: 'Runtime', sortBy: 'Sort by', votes: 'Number of votes', min: 'min', max: 'max',
    minVotes: 'Minimum number of votes', maxVotes: 'Maximum number of votes',
    excluded: 'Excluded: {genres}', makers: 'Creators:', director: 'director', actor: 'actor',
    hideKnown: 'Hide what I already know', loadNossy: 'Load Nossy scores', loadingScores: 'Loading scores\u2026',
    filmsOf: 'Films by {naam}', nothingFound: 'Nothing found',
    emptyRetry: 'No results. Try a different search term or other criteria.',
    emptyFiltered: 'No film meets your criteria ({filters}). Loosen one or clear the filters.',
    emptyTextFiltered: { one: 'There was {count} title match, but your filters ({filters}) filtered it out. Loosen one.', other: 'There were {count} title matches, but your filters ({filters}) filtered them all out. Loosen one.' },
    clearFilters: 'Clear filters', nextPage: 'Next page ({page}/{total})',
    resultsLine: '{count} results, page {page} of {total}', matchPct: '{pct}% match',
    copyBtn: 'Copy', exportLbBtn: 'Export for Letterboxd',
    lbImportHint: 'Import the CSV on Letterboxd like this: open your watchlist and choose Import. The file contains tmdbIDs, so matching is flawless.',
    inCollection: 'Already in your collection', seenBadge: 'Already seen', seenGave: 'Already seen \u00b7 you gave {score} \u2605', diep: 'Deep underground', radar: 'Under the radar',
    degelijk: 'Solidly watched', breed: 'Widely seen',
    allLangs: 'All languages', notEnglish: 'Non-English',
    qWithout: 'without {genres}', qNow: 'now', qVotesRange: '{a}\u2013{b} votes', qAll: 'everything',
    fGenre: 'genre', fExcl: 'excluded genres', fPeriod: 'period', fLang: 'language',
    fVotes: 'votes', fScore: 'score', fDuur: 'length', fHide: '"hide known"',
    needKey: 'Search needs your TMDB key. Set it up in Setup.',
    periodLabel: 'Period:', votesLabel: 'Number of votes:',
    tasteTitle: 'Fill the filters with your own taste profile', pearlTitle: 'Deep underground gems: 7.0+ with few votes',
    runtime60: '60+ min', runtime90: '90+ min', runtime120: '120+ min',
    resCount: { one: '{count} result', other: '{count} results' }, resPage: '{total} results, page {page} of {pages}',
    filmsByLine: 'Films by {naam}', ofCount: '{shown} of {total}', wis: 'clear',
  },
  winner: {
    chosenAria: 'Chosen film: {name}',
    bronTitle: { one: 'Weighted average of {count} source. Your recipe: IMDb {imdb}\u00d7, Metacritic {mc}\u00d7, TMDB {tmdb}\u00d7 (adjustable in Setup). Rotten Tomatoes does not count: it\u0027s a consensus percentage, not a score.', other: 'Weighted average of {count} sources. Your recipe: IMDb {imdb}\u00d7, Metacritic {mc}\u00d7, TMDB {tmdb}\u00d7 (adjustable in Setup). Rotten Tomatoes does not count: it\u0027s a consensus percentage, not a score.' },
    eyebrow: 'Your pick for tonight', nossy: 'Nossy', trailer: 'Trailer', more: 'more', less: 'less',
    notFoundStreaming: 'Not found on your region\u2019s streaming services',
    moreScores: '+ IMDb \u00b7 \ud83c\udf45 \u00b7 Meta', moreScoresTitle: 'More scores? Free OMDb key, set it up in Setup', endTime: 'start now = done by {t}', nowOn: 'Now on {p}', rentBuy: 'Rent/buy: {p}', provTitle: 'View watch options on JustWatch', share: 'Share', makingCard: 'Making card\u2026',
    rerollMood: 'Not feeling it? Pick again', regie: 'directed by',
    notSeenAfterAll: 'Not seen after all', onShortlist: 'On your shortlist', moreLikeThis: 'More like this',
    yearMismatch: 'Note: your list says {want}, but this is the version from {got}. Possibly the wrong match. You can re-match it in Setup.',
    shareFail: 'Generating the share card failed (the poster CDN may block this). Please try again later.',
  },
  match: {
    title: 'Tracking down the wrong film ({i} of {n})',
    listSays: 'Your list says {name}', fromYear: ' from {year}',
    nowLinked: ' Now linked to the version from {year}.', chooseBelow: ' Choose the right one below.',
    stopBtn: 'Stop', searching: 'Searching candidates\u2026', allDone: 'All checked',
    allChecked: "You've reviewed all the doubtful cases.", close: 'Close',
    noneFound: 'No film found for "{name}". This may be a TV series, and those don\u2019t belong in this film tool.',
    notAFilm: "Doesn't belong on my film list", thisIsRight: 'This one is right / skip',
    tvHint: 'Few film matches. This may be a TV series (Letterboxd sometimes sneaks those in). If none of these fit, choose "Doesn\u2019t belong on my film list".',
    yearUnknown: 'year unknown', votesShort: { one: '{n} vote', other: '{n} votes' }, current: 'Current link', choose: 'Choose {title}',
  },
  setup: {
    language: 'Language', languageHint: 'Choose the language of the tool.',
    region: 'Region, for streaming availability', regionAria: 'Streaming region',
    regionHint: 'Streaming availability differs per country: KPN or Videoland mean nothing to someone in the UK. Pick your country; the tool then fetches the right services and JustWatch links. After switching, your library\u0027s availability refreshes automatically in the background.',
    tmdbPlaceholder: 'Paste your v3 API key', saveTest: 'Save and test', testing: 'Testing\u2026',
    tmdbRejected: 'Key rejected by TMDB. Check that you\u2019re using the v3 key.',
    tmdbWorking: 'A working key is already set.',
    tmdbViaProxy: 'Posters, scores and streaming info already work: the tool handles TMDB for you. You may enter your own key, which then takes priority.',
    scoresPitch: 'Four scores instead of one',
    wizStep1: 'Request your free key at ', wizStep1b: ' and choose FREE (good for 1000 films per day).',
    wizStep2: 'Check your email and click the activation link. Without that click the key won\u0027t work.',
    wizStep3: 'Paste the key here and test:',
    singlePlaceholder: 'e.g. a1b2c3d4',
    multiToggle: 'Multiple keys? Paste them all, one per line. The tool rotates automatically.',
    omdbActive: { one: 'OMDb active \u00b7 {count} key', other: 'OMDb active \u00b7 {count} keys' },
    changeKeys: 'Change keys',
    scoresStatus: 'Scores complete for {have} of your {total} films.',
    scoresMissing: { one: '{count} film is still missing OMDb scores.', other: '{count} films are still missing OMDb scores.' },
    scoresAllDone: 'All films have their scores.',
    scoresAwaitTmdb: 'The tool is still fetching base data first; scores follow after.',
    fetchScoresNow: 'Fetch them',
    scoresFetching: 'Fetching scores: {done} of {total}',
    profiles: 'Profiles', profilesHint: 'Each their own watchlist, history and taste profile on this device. Switching reloads the tool.',
    profileDefault: 'Default', addProfile: 'Add', profileNamePlaceholder: 'e.g. Eef',
    profileNameInvalid: 'That name will not work. Stick to letters, digits and spaces, 24 characters max.',
    deleteProfileConfirm: 'Delete profile "{name}" and all its data? This cannot be undone.',
    deleteProfileAria: 'Delete profile {name}',
    invalidHint: 'Key invalid? Usually the activation link in the email hasn\u0027t been clicked yet.',
    savedFetching: 'Saved. Fetching scores.',
    savedNoBudget: 'Saved, but none of the keys has any budget left today. The tool will try again tomorrow.',
    omdbLabel: 'OMDb key (optional) for IMDb, Rotten Tomatoes & the Nossy score',
    omdbIntro1: 'TMDB provides the basics; with a free OMDb key (', omdbIntro1b: ', 1000 films per day) you also get the IMDb, Rotten Tomatoes and Metacritic scores, plus the Nossy score: the average of all available sources. ',
    omdbPlaceholder: 'Paste your OMDb key(s), one per line', testAllKeys: 'Test all keys',
    omdbExists: 'An OMDb key is already set.',
    noUsableKeys: 'No usable keys: all invalid or blocked (see below).',
    reloadData: 'Load Letterboxd data (again)', fetchData: 'Fetch film data (again)',
    fetching: 'Fetching\u2026', busy: 'Working\u2026', fetchMissing: 'Fetch missing scores',
    nossyRecipe: 'Nossy recipe: your score, your weighting', metacritic: 'Metacritic',
    themeEmphasis: 'Theme emphasis: how strongly your themes steer the recommendations',
    themeOff: 'Off, no themes', themeLight: 'Light accent', themeStandard: 'Standard',
    themeStrong: 'Emphasised', themeVeryStrong: 'Strongly theme-driven',
    backup: 'Backup', storageUsage: 'Storage in use: {mb} of \u00b1 5 MB (browser limit)', storageUsageIdb: 'Cache in use: {mb} MB (IndexedDB, with hundreds of MBs of room)', exportAll: 'Export everything (JSON)', clickToRestore: 'Click to restore.',
    ignoredCount: { one: '{count} item marked as "not a film" (excluded from recommendations and Movie night):', other: '{count} items marked as "not a film" (excluded from recommendations and Movie night):' },
    wrongFilms: { one: '{count} film with a differing year, pick the right one', other: '{count} films with a differing year, pick the right one' },
    shortFilms: { one: 'Also check {count} short film (possibly a series)', other: 'Also check {count} short films (possibly series)' },
    recheckHint: 'A match looks off? Fetch the film data again; the tool then rechecks all matches and flags films whose year differs.',
    confirmClearAll: 'Erase all local data of this tool (watchlist, cache, history, settings)?',
    confirmClearData: 'Erase watchlist, film data, ratings and history? Your TMDB key is kept.',
    pageSub: 'TMDB key, your data and backups.', title: 'Setup',
    tmdbKeyLabel: 'TMDB API key',
    tmdbIntro1: 'Request one for free at ', tmdbIntro2: ' (choose \u201cAPI Read\u201d, the short v3 key). With it the tool fetches posters, scores, trailers, recommendations and streaming services.',
    omdbIntro: 'Multiple keys? Put one per line: the tool switches automatically as soon as a key hits its daily limit.',
    omdbAria: 'OMDb API keys, one per line',
    omdbSet1: 'An OMDb key is already set.', omdbSetN: '{count} OMDb keys are set (with automatic rotation).',
    statusOk: 'works (credit available)', statusLimit: 'daily limit reached, usable again tomorrow',
    statusInvalid: 'invalid or deactivated by OMDb', statusNetwork: 'unreachable. Is an adblocker blocking omdbapi.com?',
    nossyExplain: 'The Nossy score is the weighted average of the numeric sources. By default they count equally; set your own recipe here (0 = ignore a source). Rotten Tomatoes never counts in the average (it\u0027s a consensus percentage, not a score) but stays visible on every card.',
    weightAria: 'Weight {label}', themeExplain: 'Besides genre and era, the tool learns your themes (TMDB keywords like "coming of age" or "alienation") from your highest-rated films. Set here how heavily they count in "For you" and the match scores. 0 = ignore, 1 = standard (theme \u2248 20%), 2 = strongly theme-driven.',
    restoreBackup: 'Restore backup', invalidBackup: 'Not a valid backup file from this tool.', wipeAll: 'Erase all data',
    versionLine: 'Nossy\u0027s Letterboxd Watchlist Picker, version {v}',
    footer: 'Fan-made tool, not affiliated with Letterboxd. This product uses the TMDB API but is not endorsed or certified by TMDB. Streaming availability via TMDB/JustWatch data and may differ. Everything runs locally in your browser; nothing is uploaded.',
    loaded: 'Loaded: {watchlist} watchlist \u00b7 {seen} seen \u00b7 {ratings} ratings \u00b7 {meta} with film data (TMDB) \u00b7 {ext} with scores (OMDb)',
  },
  imp: {
    title: 'What are we watching tonight?', pickSub: 'Pick.', tmdbPrompt: 'Paste your free TMDB key',
    dropHere: 'Drop your Letterboxd export here', chooseFiles: 'Choose file(s)', export: 'Export',
    dropSub: 'The whole ZIP can go in at once. The tool picks out your watchlist, watched list and ratings itself. Individual CSVs work too.',
    tryDemo: 'Try with a demo watchlist',
    privacy: 'Everything stays in your own browser. Make an export: ',
    heroSub: 'Load your Letterboxd watchlist and let the tool choose: by mood, together with friends, or smartly weighted on score.',
    step1: '<strong>Export</strong> your data on Letterboxd and drop the ZIP in above.',
    repFirst: { one: '{count} film loaded. Happy watching!', other: '{count} films loaded. Happy watching!' },
    repUpdated: 'Updated: ', repNothingNew: 'Updated. No changes since your previous export.',
    repNewWl: { one: '{count} new on your watchlist', other: '{count} new on your watchlist' },
    repGone: { one: '{count} off your watchlist', other: '{count} off your watchlist' },
    repNewRatings: { one: '{count} new rating', other: '{count} new ratings' },
    repLists: { one: '{count} personal list loaded', other: '{count} personal lists loaded' },
    repNewSeen: { one: '{count} newly seen', other: '{count} newly seen' },
    step2: '<strong>Paste your free TMDB key</strong> in Setup for posters, scores and streaming services.',
    step2Proxy: 'Optional: <strong>free OMDb keys</strong> in Setup for IMDb, Rotten Tomatoes and Metacritic scores. Can be done later too.',
    step3: '<strong>Pick.</strong> Choose a mood or let fate decide. Choosing together happens in Movie night.',
    busy: 'Working\u2026', noFiles: 'No usable files found. Expected: your Letterboxd export (ZIP) or watchlist.csv / watched.csv / ratings.csv.',
  },
};
