// Nederlands woordenboek. Geneste secties per tab/onderdeel.
export default {
  taste: {
    matchGenres: '{genres} past bij je hoogst beoordeelde films',
    aboutThemes: 'over {themes} \u2014 jouw thema\u0027s', and: ' en ',
    negGenre: 'let op: {genre} scoort bij jou juist laag',
    yourEra: 'jaren \u0027{era} is jouw tijdperk',
    nonEnglish: 'niet-Engelstalig \u2014 daar kijk jij veel van',
    strongRated: 'sterk beoordeeld ({score} bij {n} stemmen)',
    barelyRated: { one: 'let op: amper beoordeeld ({count} stem) \u2014 dat cijfer zegt weinig', other: 'let op: amper beoordeeld ({count} stemmen) \u2014 dat cijfer zegt weinig' },
    obscure: 'lekker obscuur, zoals je smaak',
  },
  share: { eyebrow: 'VANAVOND KIJKEN WIJ' },
  nav: {
    navLabel: 'Hoofdnavigatie',
    pick: 'Pick', bieb: 'Bieb', verken: 'Verken', avond: 'Avond', inzicht: 'Inzicht', setup: 'Setup',
  },
  app: {
    storageBroken: 'De browseropslag is vol of geblokkeerd \u2014 wijzigingen worden niet meer bewaard. Maak ruimte via Setup (data wissen of een kleinere watchlist) of verlaat priv\u00e9modus.',
    enriching: 'Filmdata ophalen bij TMDB\u2026 {done}/{total}', enrichErrCount: ' ({count} mislukt)', pause: 'Pauzeer',
    tmdbKeyRejected: 'TMDB wees je sleutel af. Check hem bij Setup.',
    enrichFailed: 'Ophalen filmdata liep vast: {msg}',
    omdbStopLimit: { one: 'OMDb: daglimiet bereikt op al je sleutels. Nog {count} film zonder scores \u2014 die pakt de tool de volgende keer gewoon op.', other: 'OMDb: daglimiet bereikt op al je sleutels. Nog {count} films zonder scores \u2014 die pakt de tool de volgende keer gewoon op.' },
    omdbStopInvalid: { one: 'OMDb: sleutel afgewezen op je laatste sleutel. Nog {count} film zonder scores \u2014 die pakt de tool de volgende keer gewoon op.', other: 'OMDb: sleutel afgewezen op je laatste sleutel. Nog {count} films zonder scores \u2014 die pakt de tool de volgende keer gewoon op.' },
    omdbNoScores: 'Er kwam geen enkele OMDb-score binnen (0 van {done}).{err} Zie Setup voor de testrun-knop en het foutdetail.',
    omdbLastError: ' Laatste fout: {msg}.',
    demoBanner: 'Je kijkt nu naar de <strong>demo-watchlist</strong> \u2014 even proeven hoe alles werkt.',
    demoReset: 'Demo wissen en opnieuw beginnen',
    omdbNudge: 'Je ziet nu alleen TMDB-scores. Met gratis OMDb-sleutels komen daar IMDb, Rotten Tomatoes, Metacritic en de Nossy-score bij \u2014 ',
    omdbNudgeLink: 'instellen bij Setup', omdbNudgeDismiss: 'Nee, TMDB is prima',
    needKeyNotice: 'Zonder TMDB-sleutel geen posters, scores en streamingdiensten. Stel hem in \u00e9\u00e9n minuut in bij ',
    setupLink: 'Setup',
  },
  common: {
    decade: 'Jaren \u0027{era}', showMore: 'Toon meer ({count} over)', posterAlt: 'Poster van {name}', openAria: 'Open {title}',
    back: 'Terug', close: 'Sluiten', save: 'Opslaan', cancel: 'Annuleren', stop: 'Stop',
    loading: 'Laden\u2026', search: 'Zoek', clear: 'Wis', seen: 'Gezien', shortlist: 'Shortlist',
    skip: 'Overslaan', showFilters: 'Toon filters', hideFilters: 'Verberg filters', hide: 'Verberg',
    allYears: 'Alle jaren', anyDuration: 'Elke duur', anyScore: 'Elke score',
    films_over: { one: '{count} film over', other: '{count} films over' },
  },
  sort: {
    titleAZ: 'Titel A\u2013Z', newest: 'Nieuwste eerst', oldest: 'Oudste eerst',
    highestScore: 'Hoogste score', shortest: 'Kortste eerst', longest: 'Langste eerst',
    yourRating: 'Jouw rating', bestScore: 'Beste score eerst', popular: 'Populairste eerst',
    bestMatch: 'Beste match voor jou', nossyScore: 'Nossy-score (na laden)',
  },
  mood: {
    kort: 'Korte avond', kort_desc: '105 min of korter',
    topper: 'Bewezen topper', topper_desc: 'Nossy-score 7,4+',
    parel: 'Verborgen parel', parel_desc: 'Nossy-score 7,0+ met weinig stemmen',
    klassieker: 'Klassieker', klassieker_desc: 'Van v\u00f3\u00f3r 1990',
    vers: 'Vers', vers_desc: '2020 of later',
  },
  pick: {
    title: 'Pick', mood: 'In de stemming voor\u2026', genres: 'Genres',
    onlyMyServices: 'Alleen op mijn diensten', resetFilters: 'Reset filters',
    fromYear: 'Vanaf jaar', toYear: 'Tot jaar', maxMinutes: 'Max minuten',
    minScoreEx: 'Min score (bijv. 7)', maxRuntime: 'Maximale speelduur', minScore: 'Minimale score',
    empty: 'Geen (ongekeken) films in deze selectie. Pas je filters of mood aan, of check of de filmdata al is opgehaald.',
    noSimilar: 'Niets vergelijkbaars gevonden in je (ongekeken) watchlist.',
    likePrev: 'Omdat hij lijkt op je vorige pick',
    reroll: 'Niet in de stemming \u2014 pick opnieuw', pickFilm: 'Pick een film', moodContext: 'Mood: {mood}',
    poolCount: { one: '{count} film in je pool', other: '{count} films in je pool' }, poolExcludeSeen: ' (gezien uitgesloten)',
    smartTitle: 'Hoger beoordeelde films maken meer kans; recent gepickte films minder. Geldt voor elke pick.',
    smartLabel: 'Slimme pick:', on: 'aan', off: 'uit', filters: 'Filters', filtersActive: '(actief)',
  },
  bieb: {
    title: 'Bieb', empty: 'Nog geen films',
    emptyHint: 'Laad je Letterboxd-export bij Pick, dan staat hier je hele collectie om doorheen te bladeren.',
    fromLibrary: 'Uit je bieb', yourWatchlist: 'Je watchlist', yourHistory: 'Je kijkgeschiedenis',
    watchlist: 'Watchlist', searchPlaceholder: 'Zoek op titel', searchLabel: 'Zoek in je bieb',
    sortLabel: 'Sorteer op', periodLabel: 'Periode', maxDurationLabel: 'Maximale duur',
    onStreaming: 'Op streaming:', nothingFound: 'Niets gevonden', hideSeen: 'Verberg gezien',
    noMatch: 'Geen film matcht je zoekterm en filters \u2014 probeer wat losser te filteren.',
    fromHistory: 'Uit je kijkgeschiedenis', youGave: ' \u2014 jij gaf {score} \u2605',
    header: { one: '{shown} van {count} film', other: '{shown} van {count} films' }, filtered: ' (gefilterd)',
    seenTab: 'Gezien ({count})', jij: 'jij gaf {score} \u2605',
  },
  avond: {
    title: 'Filmavond', needWatchlist: 'Eerst een watchlist',
    needWatchlistHint: 'Laad je Letterboxd-export bij Pick, dan kun je hier samen kiezen.',
    groupSpoke: 'De groep heeft gesproken.', survivedVetoes: 'Overleefde alle veto\u2019s',
    bracketWinner: 'Winnaar van het bracket', vetoRound: 'Veto-ronde',
    vetoHint: 'Geef de telefoon door na elke veto. De laatste film die overblijft, kijken jullie.',
    quarterfinal: 'Kwartfinale', semifinal: 'Halve finale', final: 'Finale',
    pot: 'De pot', myWatchlist: 'Mijn watchlist', loadOtherFriend: 'Andere vriend laden',
    loadFriendWatchlist: 'Watchlist van vriend laden', year: 'Jaar', yearFrom: 'Jaar van', yearTot: 'Jaar tot',
    from: 'van', to: 'tot', noWatchlistInFile: 'Geen watchlist gevonden in dit bestand.',
    startVeto: 'Start veto', filtersOptional: 'Filters \u00b7 optioneel', filtersActive: 'Filters \u00b7 {count} films over',
    genre: 'Genre', maxDuration: 'Maximale duur', minNossy: 'Minimale Nossy-score',
    onlyStreaming: 'Alleen op streaming', tooFew: { one: 'Nog maar {count} film over \u2014 versoepel een filter voor een volwaardige ronde.', other: 'Nog maar {count} films over \u2014 versoepel een filter voor een volwaardige ronde.' },
    overlapCount: { one: '{count} film staat op allebei jullie lijsten', other: '{count} films staan op allebei jullie lijsten' },
    overlapTooFew: ' \u2014 te weinig voor een ronde, schakel terug naar je eigen lijst',
    infoAria: 'Info over {name}',
    peek: 'Even spieken \u2014 de ronde loopt door', startBracket: 'Start bracket',
    players: 'Spelers', playerCount: 'Aantal spelers', min4: 'Minimaal 4 ongekeken films nodig in de pot.',
    filtersOpt: 'Filters {suffix}', filtersOptSuffix: '\u00b7 optioneel', filtersActiveSuffix: { one: '\u00b7 {count} film over', other: '\u00b7 {count} films over' },
  },
  inzicht: {
    title: 'Inzicht', empty: 'Nog geen data',
    emptyHint: 'Laad je watchlist bij Pick \u2014 hier verschijnt daarna je smaakprofiel.',
    subtitle: 'Jouw smaak, gelezen uit je watchlist{extra}.', andRatings: ' en ratings',
    profileTitle: 'Jouw smaakprofiel \u2014 waar de aanbevelingen op sturen',
    profileYoung: 'Nog wat pril: geef meer sterren op Letterboxd (of laad je ratings.csv) en dit profiel wordt scherper. Wat er nu is:',
    onWatchlist: 'Op je watchlist', toWatch: 'Nog te kijken',
    famDeep: 'lekker de diepte in', famMix: 'een gezonde mix van bekend en obscuur', famEstablished: 'vooral gevestigde titels',
    watchMostly: 'overwegend', watchAlso: 'graag ook', watchMainlyEn: 'vooral Engelstalig, met af en toe',
    langFamLine: 'Je kijkt {watch} <strong>{pct}% niet-Engelstalig</strong>, en qua bekendheid zit je smaak rond <strong>{votes} stemmen</strong> \u2014 {verdict}.', avgRuntime: 'Gem. speelduur',
    totalTime: 'Totale kijktijd', avgTmdb: 'Gem. TMDB-score', hours: '\u00b1{h} uur', min: '{m} min',
    genres: 'Genres', decades: 'Decennia', directorsMulti: 'Regisseurs met meerdere films op je lijst',
    countries: 'Landen', prevPick: 'Eerdere pick',
    lovesLine: 'Je valt vooral op <strong>{genres}</strong>', lovesEra: ' uit de <strong>{era}</strong>',
    dislikesLine: 'Minder jouw ding: <strong>{genres}</strong> \u2014 die worden in aanbevelingen omlaag gewogen.',
    themesLine: 'Terugkerende thema\u0027s in wat je hoog waardeert: <strong>{themes}</strong>. Die sturen "Voor jou" mee \u2014 en je kunt er actief op jagen.',
  },
  verken: {
    title: 'Verken', tabSearch: 'Zoeken', tabForYou: 'Voor jou',
    searchSub: 'Doorzoek de complete TMDB-catalogus \u2014 op titel, maker of criteria \u2014 met jouw smaakprofiel als lens.',
    forYouSub: 'Je persoonlijke aanbod uit je eigen films{ratings}. {count} suggesties, allemaal nog niet op je lijst.',
    basedOnRatings: ', op basis van wat jij 4+ sterren gaf',
    needKeyTitle: 'Eerst een TMDB-sleutel nodig',
    needKeySub: 'Doorzoek de complete filmdatabase en ontdek films buiten je watchlist.',
    needKeyBody: 'Stel je TMDB-sleutel in bij Setup \u2014 daarna kun je hier de hele catalogus doorzoeken. Laad je watchlist bij Pick voor persoonlijke aanbevelingen in "Voor jou".',
    fromOutside: 'Van buiten je lijst', detailsLoading: 'Details laden\u2026',
    backToVerken: 'Terug naar Verken', bestMatchForYou: 'Beste match voor jou',
    strongestRec: 'Sterkst aangeraden', forNowEmpty: 'Voor nu even op',
    allRatedEmpty: 'Je hebt alles beoordeeld of overgeslagen \u2014 maar TMDB is nog lang niet leeg.',
    huntThemes: 'Jaag op mijn thema\u2019s', huntThemesActive: '\u2713 Jagen op mijn thema\u2019s', hunting: 'Thema-jacht\u2026',
    yourThemes: 'Je thema\u0027s: {themes}', huntTitle: 'Haal films op die jouw sterkste thema\u0027s delen', foundOnThemes: 'Gevonden op je thema\u0027s: {themes}',
    viaProfile: 'Via jouw smaakprofiel gevonden', likeThis: 'Lijkt op', becauseYou: 'Omdat je', and: ' en ',
    loadFresh: 'Vers uit TMDB laden', loadFreshMore: 'Vers uit TMDB laden (\u00b160 nieuwe kandidaten)',
    tapping: 'Tappen\u2026', tappingTmdb: 'Tappen uit TMDB\u2026', shortlistCopied: 'Shortlist gekopieerd.',
    removeShortAria: 'Verwijder {title} van shortlist',
    rejected: 'Afgewezen ({count}) \u2014 {action}', rejHide: 'verberg', rejShow: 'bekijk en herstel',
    fromOeuvre: 'Uit het oeuvre van {name}',
    notForMe: 'Niet voor mij', viewCard: 'Bekijk kaart', similar: 'Meer zoals deze',
    nudgeMore: 'Genoteerd \u2014 je ziet nu iets meer {genre} in je aanbevelingen.',
    nudgeLess: 'Genoteerd \u2014 je ziet nu iets minder {genre} in je aanbevelingen.',
    blending: 'Mengmotor verbreedt de instroom\u2026 (vergelijkbare films, oeuvres van je favoriete regisseurs, jouw profiel)',
    inflow: 'Instroom: aanbevelingen \u00b7 vergelijkbaar \u00b7 {oeuvres} oeuvres \u00b7 jouw profiel{theme} \u2014 {count} kandidaten',
    inflowTheme: ' \u00b7 {count} op thema',
    andOthers: ' (en {count} andere)', ratedHigh: ' hoog waardeerde', onYourList: ' op je lijst hebt',
    viaRoutes: ' \u00b7 via {count} routes', showMore: 'Toon meer ({count} over)',
    hiddenPanel: '{count} overgeslagen', restore: 'Herstel {title}', restoreTitle: 'Terugzetten als aanbeveling',
  },
  zoek: {
    placeholder: 'Zoek op titel of maker \u2014 of laat leeg en filter hieronder',
    searchLabel: 'Zoek op titel of maker', onMyTaste: 'Op mijn smaak', pearlPreset: 'Pareljacht-preset',
    genres: 'Genres', period: 'Periode', language: 'Taal', minScoreLabel: 'Minimale score',
    runtime: 'Speelduur', sortBy: 'Sorteer op', votes: 'Aantal stemmen', min: 'min', max: 'max',
    minVotes: 'Minimaal aantal stemmen', maxVotes: 'Maximaal aantal stemmen',
    excluded: 'Uitgesloten: {genres}', makers: 'Makers:', director: 'regisseur', actor: 'acteur',
    hideKnown: 'Verberg wat ik al ken', loadNossy: 'Nossy-scores laden', loadingScores: 'Scores laden\u2026',
    filmsOf: 'Films van {naam}', nothingFound: 'Niets gevonden',
    emptyRetry: 'Geen resultaten \u2014 probeer een andere zoekterm of andere criteria.',
    emptyFiltered: 'Geen film voldoet aan je criteria ({filters}). Versoepel er \u00e9\u00e9n of wis de filters.',
    emptyTextFiltered: { one: 'Er was {count} titeltreffer, maar je filters ({filters}) zeefden \u0027m weg. Versoepel er \u00e9\u00e9n.', other: 'Er waren {count} titeltreffers, maar je filters ({filters}) zeefden ze allemaal weg. Versoepel er \u00e9\u00e9n.' },
    clearFilters: 'Filters wissen', nextPage: 'Volgende pagina ({page}/{total})',
    resultsLine: '{count} resultaten, pagina {page} van {total}', matchPct: '{pct}% match',
    inCollection: 'Al in je collectie', diep: 'Diep ondergronds', radar: 'Onder de radar',
    degelijk: 'Degelijk bekeken', breed: 'Breed gezien',
    allLangs: 'Alle talen', notEnglish: 'Niet-Engelstalig',
    qWithout: 'zonder {genres}', qNow: 'nu', qVotesRange: '{a}\u2013{b} stemmen', qAll: 'alles',
    fGenre: 'genre', fExcl: 'uitgesloten genres', fPeriod: 'periode', fLang: 'taal',
    fVotes: 'stemmen', fScore: 'score', fDuur: 'duur', fHide: '"verberg bekende"',
    needKey: 'Zoeken heeft je TMDB-sleutel nodig \u2014 stel die in bij Setup.',
    periodLabel: 'Periode:', votesLabel: 'Aantal stemmen:',
    tasteTitle: 'Vul de filters met je eigen smaakprofiel', pearlTitle: 'Diep ondergrondse parels: 7,0+ met weinig stemmen',
    runtime60: '60+ min', runtime90: '90+ min', runtime120: '120+ min',
    resCount: { one: '{count} resultaat', other: '{count} resultaten' }, resPage: '{total} resultaten, pagina {page} van {pages}',
    filmsByLine: 'Films van {naam}', ofCount: '{shown} van {total}', wis: 'wis',
  },
  winner: {
    chosenAria: 'Gekozen film: {name}',
    bronTitle: { one: 'Gewogen gemiddelde van {count} bron \u2014 jouw recept: IMDb {imdb}\u00d7, Metacritic {mc}\u00d7, TMDB {tmdb}\u00d7 (instelbaar bij Setup). Rotten Tomatoes telt niet mee: dat is een consensus-percentage, geen cijfer.', other: 'Gewogen gemiddelde van {count} bronnen \u2014 jouw recept: IMDb {imdb}\u00d7, Metacritic {mc}\u00d7, TMDB {tmdb}\u00d7 (instelbaar bij Setup). Rotten Tomatoes telt niet mee: dat is een consensus-percentage, geen cijfer.' },
    eyebrow: 'Jouw pick voor vanavond', nossy: 'Nossy', trailer: 'Trailer', more: 'meer', less: 'minder',
    notFoundStreaming: 'Niet gevonden bij streamingdiensten in jouw regio',
    moreScores: '+ IMDb \u00b7 \ud83c\udf45 \u00b7 Meta', moreScoresTitle: 'Meer scores? Gratis OMDb-sleutel \u2014 regel het bij Setup', nowOn: 'Nu op {p}', rentBuy: 'Huur/koop: {p}', provTitle: 'Bekijk kijkopties op JustWatch', share: 'Deel', makingCard: 'Kaart maken\u2026',
    rerollMood: 'Niet in de stemming \u2014 pick opnieuw', regie: 'regie',
    notSeenAfterAll: 'Toch niet gezien', onShortlist: 'Op je shortlist', moreLikeThis: 'Meer zoals deze',
    yearMismatch: 'Let op: jouw lijst noemt {want}, maar dit is de versie uit {got}. Mogelijk de verkeerde match \u2014 bij Setup kun je \u0027m opnieuw laten matchen.',
    shareFail: 'Deelkaart genereren lukte niet (mogelijk blokkeert de poster-CDN dit). Probeer het later opnieuw.',
  },
  match: {
    title: 'Verkeerde film opsporen \u2014 {i} van {n}',
    listSays: 'Je lijst noemt {name}', fromYear: ' uit {year}',
    nowLinked: ' Nu gekoppeld aan de versie uit {year}.', chooseBelow: ' Kies hieronder de juiste.',
    stopBtn: 'Stoppen', searching: 'Kandidaten zoeken\u2026', allDone: 'Alles nagelopen',
    allChecked: 'Je hebt alle twijfelgevallen bekeken.', close: 'Sluiten',
    noneFound: 'Geen film gevonden voor "{name}". Dit is mogelijk een tv-serie \u2014 die hoort niet in deze filmtool.',
    notAFilm: 'Hoort niet op mijn filmlijst', thisIsRight: 'Deze klopt al / overslaan',
    tvHint: 'Weinig filmtreffers \u2014 mogelijk een tv-serie (die Letterboxd soms meesmokkelt). Klopt geen van deze, kies dan "Hoort niet op mijn filmlijst".',
    yearUnknown: 'jaar onbekend', votesShort: { one: '{n} stem', other: '{n} stemmen' }, current: 'Huidige koppeling', choose: 'Kies {title}',
  },
  setup: {
    language: 'Taal', languageHint: 'Kies de taal van de tool.',
    region: 'Regio \u2014 voor het streamingaanbod', regionAria: 'Streaming-regio',
    regionHint: 'Streamingaanbod verschilt per land: een Brit heeft niks aan KPN of Videoland. Kies je land; de tool haalt dan de juiste diensten en JustWatch-links op. Na een wissel ververst het aanbod van je bibliotheek automatisch op de achtergrond.',
    tmdbPlaceholder: 'Plak je v3 API-sleutel', saveTest: 'Opslaan en testen', testing: 'Testen\u2026',
    tmdbRejected: 'Sleutel afgewezen door TMDB. Check of je de v3-sleutel gebruikt.',
    tmdbWorking: 'Er staat al een werkende sleutel ingesteld.',
    tmdbViaProxy: 'Posters, scores en streaminginfo werken al \u2014 de tool regelt TMDB voor je. Een eigen sleutel invullen mag (die krijgt dan voorrang), maar hoeft niet.',
    scoresPitch: 'Vier scores in plaats van \u00e9\u00e9n',
    wizStep1: 'Vraag je gratis sleutel aan bij ', wizStep1b: ' \u2014 kies FREE, goed voor 1000 films per dag.',
    wizStep2: 'Check je mail en klik de activatielink \u2014 zonder die klik doet de sleutel het niet.',
    wizStep3: 'Plak de sleutel hier en test:',
    singlePlaceholder: 'bijv. a1b2c3d4',
    multiToggle: 'Meerdere sleutels? Plak ze allemaal, \u00e9\u00e9n per regel \u2014 de tool wisselt automatisch.',
    omdbActive: { one: 'OMDb actief \u00b7 {count} sleutel', other: 'OMDb actief \u00b7 {count} sleutels' },
    changeKeys: 'Wijzig sleutels',
    invalidHint: 'Sleutel ongeldig? Meestal is de activatielink in de mail nog niet aangeklikt.',
    savedFetching: 'Opgeslagen \u2014 scores worden opgehaald.',
    savedNoBudget: 'Opgeslagen \u2014 maar geen enkele sleutel heeft n\u00fa nog tegoed; morgen probeert de tool automatisch verder.',
    omdbLabel: 'OMDb-sleutel (optioneel) \u2014 voor IMDb, Rotten Tomatoes & de Nossy-score',
    omdbIntro1: 'TMDB levert de basis; met een gratis OMDb-sleutel (', omdbIntro1b: ', 1000 films per dag) komen daar de IMDb-, Rotten Tomatoes- en Metacritic-scores bij \u2014 en daarmee de Nossy-score: het gemiddelde van alle beschikbare bronnen. ',
    omdbPlaceholder: 'Plak je OMDb-sleutel(s), \u00e9\u00e9n per regel', testAllKeys: 'Test alle sleutels',
    omdbExists: 'Er staat al een OMDb-sleutel ingesteld.',
    noUsableKeys: 'Geen bruikbare sleutels: allemaal ongeldig of geblokkeerd (zie hieronder).',
    reloadData: 'Letterboxd-data (opnieuw) laden', fetchData: 'Filmdata (opnieuw) ophalen',
    fetching: 'Bezig met ophalen\u2026', busy: 'Bezig\u2026', fetchMissing: 'Ontbrekende scores ophalen',
    nossyRecipe: 'Nossy-recept \u2014 jouw score, jouw weging', metacritic: 'Metacritic',
    themeEmphasis: 'Thema-nadruk \u2014 hoe sterk sturen je thema\u0027s de aanbevelingen',
    themeOff: 'Uit \u2014 geen thema\u0027s', themeLight: 'Licht accent', themeStandard: 'Standaard',
    themeStrong: 'Nadrukkelijk', themeVeryStrong: 'Sterk themagedreven',
    backup: 'Back-up', storageUsage: 'Opslag in gebruik: {mb} van \u00b1 5 MB (browserlimiet)', storageUsageIdb: 'Cache in gebruik: {mb} MB \u2014 in IndexedDB, met honderden MB\u0027s ruimte', exportAll: 'Exporteer alles (JSON)', clickToRestore: 'Klik om terug te zetten.',
    ignoredCount: { one: '{count} item gemarkeerd als "geen film" (uitgesloten uit aanbevelingen en Avond):', other: '{count} items gemarkeerd als "geen film" (uitgesloten uit aanbevelingen en Avond):' },
    wrongFilms: { one: '{count} mogelijk verkeerde film \u2014 kies de juiste', other: '{count} mogelijk verkeerde films \u2014 kies de juiste' },
    confirmClearAll: 'Alle lokale data van deze tool wissen (watchlist, cache, geschiedenis, instellingen)?',
    confirmClearData: 'Watchlist, filmdata, ratings en geschiedenis wissen? Je TMDB-sleutel blijft bewaard.',
    pageSub: 'TMDB-sleutel, je data en back-ups.', title: 'Setup',
    tmdbKeyLabel: 'TMDB API-sleutel',
    tmdbIntro1: 'Gratis aan te vragen via ', tmdbIntro2: ' (kies \u201cAPI Read\u201d \u2014 de korte v3-sleutel). Hiermee haalt de tool posters, scores, trailers, aanbevelingen en streamingdiensten op.',
    omdbIntro: 'Meerdere sleutels? Zet er \u00e9\u00e9n per regel: de tool schakelt automatisch door zodra een sleutel z\u0027n daglimiet raakt.',
    omdbAria: 'OMDb API-sleutels, \u00e9\u00e9n per regel',
    omdbSet1: 'Er staat al een OMDb-sleutel ingesteld.', omdbSetN: 'Er staan {count} OMDb-sleutels ingesteld (met automatische rotatie).',
    statusOk: 'werkt (tegoed beschikbaar)', statusLimit: 'daglimiet bereikt \u2014 morgen weer bruikbaar',
    statusInvalid: 'ongeldig of gedeactiveerd door OMDb', statusNetwork: 'onbereikbaar \u2014 blokkeert een adblocker omdbapi.com?',
    nossyExplain: 'De Nossy-score is het gewogen gemiddelde van de cijfer-bronnen. Standaard tellen ze gelijk; stel hier je eigen recept in (0 = bron negeren). Rotten Tomatoes telt nooit mee in het gemiddelde \u2014 dat is een consensus-percentage, geen cijfer \u2014 maar blijft zichtbaar op elke kaart.',
    weightAria: 'Gewicht {label}', themeExplain: 'Naast genre en tijdperk leert de tool je thema\u0027s (TMDB-trefwoorden als "coming of age" of "vervreemding") uit je hoogst beoordeelde films. Bepaal hier hoe zwaar die meewegen in "Voor jou" en de matchscores. 0 = negeren, 1 = standaard (thema \u2248 20%), 2 = sterk themagedreven.',
    restoreBackup: 'Herstel back-up', invalidBackup: 'Geen geldig back-upbestand van deze tool.', wipeAll: 'Wis alle data',
    versionLine: 'Nossy\u0027s Letterboxd Watchlist Picker \u2014 versie {v}',
    footer: 'Fan-made tool, niet verbonden aan Letterboxd. This product uses the TMDB API but is not endorsed or certified by TMDB. Streamingaanbod via TMDB/JustWatch-data en kan afwijken. Alles draait lokaal in je browser; er wordt niets ge\u00fcploud.',
    loaded: 'Geladen: {watchlist} watchlist \u00b7 {seen} gezien \u00b7 {ratings} ratings \u00b7 {meta} met filmdata (TMDB) \u00b7 {ext} met scores (OMDb)',
  },
  imp: {
    title: 'Wat kijken we vanavond?', pickSub: 'Pick.', tmdbPrompt: 'Plak je gratis TMDB-sleutel',
    dropHere: 'Sleep je Letterboxd-export hierheen', chooseFiles: 'Kies bestand(en)', export: 'Exporteer',
    dropSub: 'De hele ZIP mag in \u00e9\u00e9n keer \u2014 de tool vist watchlist, gezien-lijst en ratings er zelf uit. Losse CSV\u2019s kunnen ook.',
    tryDemo: 'Probeer met demo-watchlist',
    privacy: 'Alles blijft in je eigen browser. Export maken: ',
    heroSub: 'Laad je Letterboxd-watchlist en laat de tool kiezen \u2014 op mood, samen met vrienden, of slim gewogen op score.',
    step1: '<strong>Exporteer</strong> je data op Letterboxd en sleep de ZIP hierboven naar binnen.',
    step2: '<strong>Plak je gratis TMDB-sleutel</strong> bij Setup voor posters, scores en streamingdiensten.',
    step2Proxy: 'Optioneel: <strong>gratis OMDb-sleutels</strong> bij Setup voor IMDb-, Rotten Tomatoes- en Metacritic-scores \u2014 kan ook later.',
    step3: '<strong>Pick.</strong> Kies een mood of laat het lot beslissen \u2014 samen kiezen kan bij Avond.',
    busy: 'Bezig\u2026', noFiles: 'Geen bruikbare bestanden gevonden. Verwacht: je Letterboxd-export (ZIP) of watchlist.csv / watched.csv / ratings.csv.',
  },
};
